(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SPORT_STANDINGS_CORE=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const items=[
['eredivisie','voetbal','Eredivisie','ned.1'],['premier-league','voetbal','Premier League','eng.1'],['champions','voetbal','Champions League','uefa.champions'],['europa','voetbal','Europa League','uefa.europa'],['conference','voetbal','Conference League','uefa.europa.conf'],
['wk','voetbal','WK','fifa.world'],['ek','voetbal','EK','uefa.euro'],['nations','voetbal','Nations League','uefa.nations'],['wk-vrouwen','voetbal','WK vrouwen','fifa.wwc'],['ek-vrouwen','voetbal','EK vrouwen','uefa.weuro'],['nations-vrouwen','voetbal','Nations League vrouwen','uefa.w.nations']
].map(([id,sport,name,slug])=>({id,sport,name,slug,kind:'football',source:'ESPN',url:`https://www.espn.com/soccer/standings/_/league/${slug}`,tournament:!['eredivisie','premier-league','champions','europa','conference'].includes(id)}));
items.push(
{id:'f1-drivers',sport:'f1',name:'Coureurs',kind:'f1',type:'drivers',source:'Jolpica',url:'https://api.jolpi.ca/ergast/f1/current/driverStandings.json'},
{id:'f1-constructors',sport:'f1',name:'Constructeurs',kind:'f1',type:'constructors',source:'Jolpica',url:'https://api.jolpi.ca/ergast/f1/current/constructorStandings.json'},
{id:'darts-merit',sport:'darts',name:'Order of Merit',kind:'merit',source:'Darts Rankings',url:'https://www.dartsrankings.com/lastranking'},
{id:'darts-premier',sport:'darts',name:'Premier League',kind:'darts-league',source:'Mastercaller',url:'https://mastercaller.nl/toernooien/premier-league/2026/stand'},
{id:'motogp-riders',sport:'motogp',name:'Coureurs',kind:'motogp',source:'MotoGP',url:'https://stats.motogp.com/en/world-standing'},
{id:'handbal-men',sport:'handbal',name:'Champions League heren',kind:'handball',source:'EHF',url:'https://ehfcl.eurohandball.com/men/2026-27/standings/'},
{id:'handbal-euro-men',sport:'handbal',name:'EK heren',kind:'handball',season:'2026',archived:true,source:'EHF',url:'https://ehfeuro.eurohandball.com/men/2026/standings/Xg2Ubz1_S9dxy0p0unxCBg/final-tournament/'},
{id:'handbal-euro-women',sport:'handbal',name:'EK dames',kind:'handball',season:'2024',archived:true,source:'EHF',url:'https://ehfeuro.eurohandball.com/women/2024/standings/R-saEwRJFutIKedhnRuDpg/FinalTournament/'},
{id:'handbal-world-men',sport:'handbal',name:'WK heren',kind:'finalranking',season:'2025',archived:true,source:'IHF',url:'https://www.ihf.info/media-center/events/29th-ihf-mens-world-championship'},
{id:'handbal-world-women',sport:'handbal',name:'WK dames',kind:'finalranking',season:'2025',archived:true,source:'IHF',url:'https://www.ihf.info/index.php/media-center/events/27th-ihf-womens-world-championship'},
{id:'handbal-women',sport:'handbal',name:'Champions League dames',kind:'handball',source:'EHF',url:'https://ehfcl.eurohandball.com/women/2026-27/standings/'}
);
function football(data){const groups=[];function visit(node){const entries=node.standings?.entries||[];if(entries.length){const rows=entries.map(e=>{const stat=n=>{let v=e.stats?.find(s=>s.name===n)?.value;return Number.isFinite(Number(v))?Number(v):null;};return{rank:stat('rank'),name:e.team?.displayName||e.team?.name,played:stat('gamesPlayed')??((stat('wins')||0)+(stat('ties')||0)+(stat('losses')||0)),wins:stat('wins'),draws:stat('ties'),losses:stat('losses'),diff:stat('pointDifferential'),points:stat('points')};}).filter(r=>r.name&&r.rank>0).sort((a,b)=>a.rank-b.rank);if(rows.length)groups.push({name:node.name||'Stand',rows});}(node.children||[]).forEach(visit);}visit(data);return{season:data.season?.displayName||String(data.season?.year||''),year:data.season?.year,groups};}
function f1(data,item){const list=data.MRData?.StandingsTable?.StandingsLists?.[0];if(!list)return{groups:[]};const rows=(item.type==='drivers'?list.DriverStandings:list.ConstructorStandings||[]).map(e=>({rank:Number(e.position),name:item.type==='drivers'?`${e.Driver.givenName} ${e.Driver.familyName}`:e.Constructor.name,team:e.Constructors?.map(t=>t.name).join(', ')||'',points:Number(e.points),wins:Number(e.wins)}));return{season:String(list.season),year:Number(list.season),round:list.round,groups:rows.length?[{name:'Kampioenschap',rows}]:[]};}
function matches(data){return(data.events||[]).map(e=>{let c=e.competitions?.[0],teams=c?.competitors||[];let home=teams.find(t=>t.homeAway==='home')||teams[0],away=teams.find(t=>t.homeAway==='away')||teams[1];return{id:e.id,date:e.date,round:e.season?.slug||c?.type?.text||e.week?.text||'',name:e.name||'',home:home?.team?.displayName||'',away:away?.team?.displayName||'',score:c?.status?.type?.completed?`${home?.score??'–'} – ${away?.score??'–'}`:null,completed:!!c?.status?.type?.completed};}).filter(e=>e.home&&e.away&&Number.isFinite(Date.parse(e.date))).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));}
return{items,football,f1,matches};
});
